### ISSUE TITLE
Unable to install module

### ISSUE THREAD

**Issue by r-valyar** [sp0ken/token-action-hud-forbidden-lands#1]
I am receiving the following error when attempting to in stall the module

![image](https://github.com/sp0ken/token-action-hud-forbidden-lands/assets/63558984/37bc32b1-4f87-4bb5-ac79-a1379f4967d6)

![image](https://github.com/sp0ken/token-action-hud-forbidden-lands/assets/63558984/dec13980-40c7-48dd-83ac-60ae0e6df678)

**Comment by sp0ken** [comment]
It should be fixed in the latest release (0.3). Let me know how it goes.

**Comment by r-valyar** [comment]
Works like a charm!!!! :) Thank you for the prompt update!
