### ISSUE TITLE
Combat Group does not show up for some Actors in Forbidden Lands

### ISSUE THREAD

**Issue by Thiudans** [sp0ken/token-action-hud-forbidden-lands#2]
Some actors do not have the Combat Group even though they have a weapon in their inventory on their character sheet. Other characters do have the Combat Group. I noticed that no weapons, actions or armor show up under the players who do not have the Combat group. (I have to unlock the HUD to get the Combat group to even appear.) Players that work have those entries.

**Comment by Thiudans** [comment]
<img width="700" alt="Working Player" src="https://github.com/sp0ken/token-action-hud-forbidden-lands/assets/19670356/d3e31447-8514-43f4-b5b1-3a9ff8afb7c3">
<img width="588" alt="Non-Working Player" src="https://github.com/sp0ken/token-action-hud-forbidden-lands/assets/19670356/8bbae76f-fb98-4813-a2b3-ecd1bb2355aa">

**Comment by sp0ken** [comment]
Hi @Thiudans,

Could you send me a screenshot of the two actors' sheet?

**Comment by Thiudans** [comment]
This is the non-worling character: 
<img width="666" alt="Screenshot 2024-05-06 at 07 23 42" src="https://github.com/sp0ken/token-action-hud-forbidden-lands/assets/19670356/97f86aa6-1422-4880-b2e6-b6f6fa34a6e6">
<img width="670" alt="Screenshot 2024-05-06 at 07 23 51" src="https://github.com/sp0ken/token-action-hud-forbidden-lands/assets/19670356/0f9bac8e-c265-4439-923a-f269a8d9967d">
<img width="668" alt="Screenshot 2024-05-06 at 07 24 02" src="https://github.com/sp0ken/token-action-hud-forbidden-lands/assets/19670356/443b9c3c-1a92-4e54-9162-88393cf6678c">
<img width="664" alt="Screenshot 2024-05-06 at 07 24 11" src="https://github.com/sp0ken/token-action-hud-forbidden-lands/assets/19670356/23626dec-cdae-49d4-8a96-369e04f6b866">

**Comment by Thiudans** [comment]
This is the working character: 
<img width="668" alt="Screenshot 2024-05-06 at 07 26 51" src="https://github.com/sp0ken/token-action-hud-forbidden-lands/assets/19670356/23bc00cf-a7c7-46cf-99dd-fc796d3e0baf">
<img width="667" alt="Screenshot 2024-05-06 at 07 27 03" src="https://github.com/sp0ken/token-action-hud-forbidden-lands/assets/19670356/152c941e-362d-4273-86c3-12ddb7c99394">
<img width="669" alt="Screenshot 2024-05-06 at 07 27 11" src="https://github.com/sp0ken/token-action-hud-forbidden-lands/assets/19670356/1abf812a-f5ad-4008-8a87-7d5aaa5d65f2">
<img width="670" alt="Screenshot 2024-05-06 at 07 27 21" src="https://github.com/sp0ken/token-action-hud-forbidden-lands/assets/19670356/4701e17e-600b-49be-95be-a1b5df0eed90">

**Comment by Thiudans** [comment]
Hi, I get you are probably busy, but is there any update, is there any other information I can give you?

Thanks!

**Comment by sp0ken** [comment]
It should be fixed in the latest version. 

The issue was with the fact that your first token didn't have an armor.
