### ISSUE TITLE
Update compatibility for FVTT 12

### ISSUE THREAD

**Issue by r-valyar** [sp0ken/token-action-hud-forbidden-lands#4]
FL system and modules are now updated for V12, I would like to place a suggestion to update this module for V12.

**Comment by sp0ken** [comment]
Did you encounter a specific issue related to either Foundry v12 or FBL v12?

**Comment by r-valyar** [comment]
I didn't observe any issues when I was testing the world in v12. All was rolling fine from the Token HUD for PC and NPCs

**Comment by brunocalado** [comment]
If it is working well, can you please update just the manifest? It's giving a warning
![image](https://github.com/user-attachments/assets/7616b53d-84c7-48ea-a457-1d285e40e409)

**Comment by JeffAroma** [comment]
I'll update it in the coming days

**Comment by sp0ken** [comment]
I'll update it in the coming days.

**Comment by sp0ken** [comment]
The latest version (v0.6) should fix the issue
